### ISSUE TITLE
nextflow id isn't captured

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/nextflow-lamin-usecases#13]
It seems that `session_id` evaluates to `"nextflow"`:

<img width="818" alt="image" src="https://github.com/laminlabs/nextflow-lamin-usecases/assets/16916678/7cdeeb7d-c1ef-4d84-8088-a2b2b3bd8951">

Because, looking into the database table, it shows `"nextflow"` for `run.reference`.

<img width="819" alt="image" src="https://github.com/laminlabs/nextflow-lamin-usecases/assets/16916678/70c6d96e-91d2-4c4b-b61e-acd3a768eb0d">

Something is off, here, right, @Zethson? 🤔

**Comment by Zethson** [comment]
.. That's weird and not intended. I'll look into it.

**Comment by Zethson** [comment]
```
⋊>   nextflow log | awk '/lamin_rnaseq/{print $8}'                                                                                         
22be0b9f-1fdc-499e-b85a-05974464e876
```

works locally so I'll have to dig into it

**Comment by falexwolf** [comment]
And it's also writing it to the db successfully locally?

**Comment by falexwolf** [comment]
Trying to fix here: https://github.com/laminlabs/nextflow-lamin-usecases/pull/14

**Comment by falexwolf** [comment]
Seems to be fixed with this PR now!
