### ISSUE TITLE
Add screenshot of report in the UI

### ISSUE THREAD

**Issue by Zethson** [laminlabs/nextflow-lamin-usecases#34]
https://laminlabs.slack.com/archives/C04U9RJQ7C1/p1717071262914059

See https://lamin.ai/navatx/sentseq-dev/transform/Gssk9pqTV5uYKrfn

We don't want to hit `laminlabs/lamindata` in the CI. Therefore, we're gonna do it properly once and register it with `laminlabs/lamindata` but still use the local instance in the CI. Then we link to `laminlabs/lamindata` in the docs which is basically a static snapshot of this.

We also want to track the registration script which is currently `register_mcmicro_run.py` like it has been done for Nava.

- [ ] Rewrite the local instance scripts in a way how it's been done for Nava
- [ ] Test it with `laminlabs/lamin-dev`
- [ ] Run it for `laminlabs/lamindata`

**Comment by falexwolf** [comment]
As important as the screenshot is linking the run.

Can you please do everything based on `laminlabs/lamindata` so that it becomes visible to users browsing it?
